stages:
  - test
  - build
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

variables:
  PDM_CACHE_DIR: ${CI_PROJECT_DIR}/.pdm-cache

image: python:3.11

before_script:
  - python -m pip install pdm


test:linux:
  stage: test
  script:
    - pdm sync --clean
    - pdm run pytest --cov=hg_setup tests

test:real-life:
  stage: test
  script:
    - python -m pip install uv
    - uv tool install mercurial --with hg-git --with hg-evolve
    - uv tool install .
    - export PATH=/root/.local/bin:$PATH
    - hg-setup init --auto
    - cd $HOME
    - hg clone https://github.com/fluiddyn/hg-setup.git
    - cd hg-setup


build:package:
  stage: build
  script:
    - pdm config cache_dir ${PDM_CACHE_DIR}
    - pdm build || pdm lock --group :all --refresh
  needs: []
  artifacts:
    when: always
    paths:
      - pdm.lock
      - dist
    expire_in: 24 hrs
  cache:
    when: always
    key: pdmcache-$CI_COMMIT_BRANCH
    paths:
      - ${PDM_CACHE_DIR}


# manually set PDM_PUBLISH_PASSWORD in web interface to your pypi API token
release:package:
  stage: release
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: on_success
  variables:
    PDM_PUBLISH_USERNAME: __token__
  script:
    - pdm publish --no-build
  needs: [ "build:package" ]
